### ISSUE TITLE
mvn install issue

### ISSUE THREAD

**Issue by Yongyao** [ESIPFed/eskg#9] opened 2017-03-27 16:31 UTC
After I pulled the code to my local machine, and run "mvn clean install". The system gives me the following error.

[ERROR] Failed to execute goal on project eskg: Could not resolve dependencies for project org.esipfed:eskg:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.allenai.openie:openie_2.11:jar:4.2.6, org.allenai.openie:openie_2.11:pom:4.2.6: Could not find artifact org.allenai.openie:openie_2.11:jar:4.2.6 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by lewismc** [comment] 2017-03-27 16:44
You need to build it locally
https://github.com/allenai/openie-standalone
Some of the code we will be working with here is not yet stable and published... so you may need to pull the source and puplish it to your local Maven repository in ~/.m2

**Comment by lewismc** [comment] 2017-03-27 16:45
Once you've built it and tried it out then please close this issue. Thanks.

**Comment by Yongyao** [comment] 2017-03-27 17:55
@lewismc I pulled the source code of OpenIE to my local machine, and followed the instructions by running "sbt compile & sbt publishM2", but the error still exists.

Failed to execute goal on project eskg: Could not resolve dependencies for project org.esipfed:eskg:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.allenai.openie:openie_2.11:jar:4.2.6, org.allenai.openie:openie_2.11:pom:4.2.6: Failure to find org.allenai.openie:openie_2.11:jar:4.2.6 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by lewismc** [comment] 2017-03-27 18:16
@Yongyao are you running ESKG off of master branch?
```
lmcgibbn@LMC-056430 /usr/local/eskg(master) $ mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building eskg 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/apache/any23/plugins/apache-any23-basic-crawler/2.1-SNAPSHOT/maven-metadata.xml
Downloading: https://repository.apache.org/content/repositories/snapshots/org/apache/any23/plugins/apache-any23-basic-crawler/2.1-SNAPSHOT/maven-metadata.xml
Downloaded: https://repository.apache.org/content/repositories/snapshots/org/apache/any23/plugins/apache-any23-basic-crawler/2.1-SNAPSHOT/maven-metadata.xml (2 KB at 2.0 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/apache/any23/apache-any23/2.1-SNAPSHOT/maven-metadata.xml
Downloading: https://repository.apache.org/content/repositories/snapshots/org/apache/any23/apache-any23/2.1-SNAPSHOT/maven-metadata.xml
Downloaded: https://repository.apache.org/content/repositories/snapshots/org/apache/any23/apache-any23/2.1-SNAPSHOT/maven-metadata.xml (2 KB at 2.7 KB/sec)
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ eskg ---
[INFO] Deleting /usr/local/eskg/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ eskg ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ eskg ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 6 source files to /usr/local/eskg/target/classes
[ERROR] error reading /Users/lmcgibbn/.m2/repository/org/apache/james/apache-mime4j-core/0.7/apache-mime4j-core-0.7.jar; invalid LOC header (bad signature)
[ERROR] error reading /Users/lmcgibbn/.m2/repository/org/apache/commons/commons-compress/1.3/commons-compress-1.3.jar; invalid LOC header (bad signature)
[INFO]
[INFO] --- forbiddenapis:1.8:check (default) @ eskg ---
[INFO] Scanning for classes to check...
[INFO] Reading bundled API signatures: jdk-unsafe
[INFO] Reading bundled API signatures: jdk-deprecated
[INFO] Reading bundled API signatures: jdk-system-out
[INFO] Loading classes to check...
[INFO] Scanning for API signatures and dependencies...
[INFO] Scanned 4 (and 288 related) class file(s) for forbidden API invocations (in 0.11s), 0 error(s).
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ eskg ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /usr/local/eskg/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ eskg ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- forbiddenapis:1.8:testCheck (default) @ eskg ---
[INFO] Scanning for classes to check...
[WARNING] Classes directory does not exist, forbiddenapis check skipped: /usr/local/eskg/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ eskg ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ eskg ---
[INFO] Building jar: /usr/local/eskg/target/eskg-1.0-SNAPSHOT.jar
[INFO]
[INFO] --- maven-jar-plugin:3.0.2:test-jar (default) @ eskg ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /usr/local/eskg/target/eskg-1.0-SNAPSHOT-tests.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ eskg ---
[INFO] Installing /usr/local/eskg/target/eskg-1.0-SNAPSHOT.jar to /Users/lmcgibbn/.m2/repository/org/esipfed/eskg/1.0-SNAPSHOT/eskg-1.0-SNAPSHOT.jar
[INFO] Installing /usr/local/eskg/pom.xml to /Users/lmcgibbn/.m2/repository/org/esipfed/eskg/1.0-SNAPSHOT/eskg-1.0-SNAPSHOT.pom
[INFO] Installing /usr/local/eskg/target/eskg-1.0-SNAPSHOT-tests.jar to /Users/lmcgibbn/.m2/repository/org/esipfed/eskg/1.0-SNAPSHOT/eskg-1.0-SNAPSHOT-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.423 s
[INFO] Finished at: 2017-03-27T11:15:47-07:00
[INFO] Final Memory: 28M/273M
[INFO] ------------------------------------------------------------------------
```

**Comment by Yongyao** [comment] 2017-03-27 18:22
yes, I do. I am trying to add the "upload ontology to esip portal" function here.

**Comment by lewismc** [comment] 2017-03-27 19:07
OK I get it. Mmmmm, I am struggling to get a solution right now as it is working fine for me locally. Can you work on setting up a TravisCI build?
https://docs.travis-ci.com/user/languages/java/
You can take our configuration on Mudrod as an example
https://github.com/mudrod/mudrod/blob/master/.travis.yml

**Comment by lewismc** [comment] 2017-04-26 05:31
Hi @Yongyao OK so it looks like the Travis CI builds also reproduce your issue. Lets take some time to look through this tomorrow shall we? Apologies about this.
On my end I must have some dependencies installed locally and hence everything compiles and resolves successfully.
The artifacts are not being found on Maven2 artifact server so we need to address this.

**Closed as completed** 2017-05-16 19:23 UTC
Labels: build
